# Generated by Django 6.0.2 on 2026-03-03 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Incubation, Initiative",
                        max_length=255,
                        verbose_name="Type de projet",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de projet",
                "verbose_name_plural": "Catégories de projets",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du projet"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Résumé court"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Contenu riche")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("UPCOMING", "À venir"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
    ]
