from django.core.management.base import BaseCommand
from apps.organization.models import OrganizationNode

NODES_DATA = [
    {
        "id": "c6221e82-7191-4e6f-a9e8-8c452aa3f230",
        "name": "Capital of Fusion",
        "slug": "capital-of-fusion",
        "type": "ROOT",
        "parent_id": null,
        "description": "Capital of Fusion rassemble les pôles et les acteurs de la danse.",
        "short_description": "École nationale de danse — Bachata, Salsa, Kizomba.",
        "content": "",
        "cta_text": "Découvrir",
        "cta_url": "/explore/",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#04768a",
        "planet_scale": 2.2,
        "orbit_radius": 0.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "677e350e-f92b-44e1-b1bd-b65a19ed7113",
        "name": "BachataVibe Paris",
        "slug": "bachatavibe-paris",
        "type": "BRANCH",
        "parent_id": "c6221e82-7191-4e6f-a9e8-8c452aa3f230",
        "description": "Cours réguliers et événements à Paris.",
        "short_description": "Pôle Paris — cours et soirées.",
        "content": "",
        "cta_text": "Voir les cours",
        "cta_url": "/cours/",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#ec4899",
        "planet_scale": 0.6,
        "orbit_radius": 4.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 0.3,
        "is_visible_3d": false
    },
    {
        "id": "a50c40dd-4b3a-4b33-b3e2-00e729bad5a0",
        "name": "BachataVibe Lyon",
        "slug": "bachatavibe-lyon",
        "type": "BRANCH",
        "parent_id": "c6221e82-7191-4e6f-a9e8-8c452aa3f230",
        "description": "",
        "short_description": "Pôle Lyon.",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#3b82f6",
        "planet_scale": 0.5,
        "orbit_radius": 5.5,
        "orbit_speed": 0.15,
        "orbit_phase": 1.5,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": false
    },
    {
        "id": "da1d5c33-8b99-4f90-aac3-d5f27abcf9c2",
        "name": "CAPITAL OF FUSION FRANCE",
        "slug": "capital-of-fusion-france",
        "type": "ROOT",
        "parent_id": null,
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#04768a",
        "planet_scale": 0.8,
        "orbit_radius": 10.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "1527367a-b025-4cf4-b653-0670dc7cd7e6",
        "name": "BRANCHES OFFICIELLES",
        "slug": "branches-officielles",
        "type": "BRANCH",
        "parent_id": "da1d5c33-8b99-4f90-aac3-d5f27abcf9c2",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#22c55e",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": false
    },
    {
        "id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "name": "BACHATA VIBE",
        "slug": "bachata-vibe",
        "type": "BRANCH",
        "parent_id": "1527367a-b025-4cf4-b653-0670dc7cd7e6",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#eab308",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": false
    },
    {
        "id": "0d74d40b-252d-4e51-914b-4c76ae73aef0",
        "name": "Bachata Vibe Experience",
        "slug": "bachata-vibe-experience",
        "type": "EVENT",
        "parent_id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "description": "Fiche détaillée pour Bachata Vibe Experience",
        "short_description": "Description courte de Bachata Vibe Experience",
        "content": "Contenu détaillé de Bachata Vibe Experience",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "wire",
        "planet_color": "#f97316",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "d542c2c9-f2c2-4001-ae6e-aa44145884c6",
        "name": "Bachata Vibe Paris Hebdo",
        "slug": "bachata-vibe-paris-hebdo",
        "type": "EVENT",
        "parent_id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "description": "Fiche détaillée pour Bachata Vibe Paris Hebdo",
        "short_description": "Description courte de Bachata Vibe Paris Hebdo",
        "content": "Contenu détaillé de Bachata Vibe Paris Hebdo",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#ef4444",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "24e70569-d394-4686-a3db-99b5b5598899",
        "name": "Dominican Vibe",
        "slug": "dominican-vibe",
        "type": "EVENT",
        "parent_id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "description": "Fiche détaillée pour Dominican Vibe",
        "short_description": "Description courte de Dominican Vibe",
        "content": "Contenu détaillé de Dominican Vibe",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#6366f1",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "1d774525-2261-4065-b24a-797db640110d",
        "name": "Paris Bachata Festival",
        "slug": "paris-bachata-festival",
        "type": "EVENT",
        "parent_id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#8b5cf6",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "86472f21-3ef0-4aa6-90ab-cbeb92ccd149",
        "name": "Jack n' Jill Vibe",
        "slug": "jack-n-jill-vibe",
        "type": "EVENT",
        "parent_id": "1d774525-2261-4065-b24a-797db640110d",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "glb",
        "planet_type": "wire",
        "planet_color": "#d946ef",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "fb07ce25-03c1-4034-873f-dc07f1e66c71",
        "name": "Street Battle",
        "slug": "street-battle",
        "type": "EVENT",
        "parent_id": "1d774525-2261-4065-b24a-797db640110d",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "glb",
        "planet_type": "wire",
        "planet_color": "#14b8a6",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "904d79ff-0160-4266-b67b-bfea54962550",
        "name": "Social World Cup",
        "slug": "social-world-cup",
        "type": "EVENT",
        "parent_id": "1d774525-2261-4065-b24a-797db640110d",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#f43f5e",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "0e6a1a14-9a3a-4ce8-ba84-b223211c060e",
        "name": "Experience Palmeraie",
        "slug": "experience-palmeraie",
        "type": "EVENT",
        "parent_id": "1d774525-2261-4065-b24a-797db640110d",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#a855f7",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "1c9e7330-fe93-42ec-bf08-6c1bed4b017b",
        "name": "Bachata Vibe Lyon",
        "slug": "bachata-vibe-lyon",
        "type": "EVENT",
        "parent_id": "2493569c-9787-4ae5-9470-e9d42cdfebe8",
        "description": "Fiche détaillée pour Bachata Vibe Lyon",
        "short_description": "Description courte de Bachata Vibe Lyon",
        "content": "Contenu détaillé de Bachata Vibe Lyon",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#ec4899",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "77da718e-86fe-461d-b416-435188f57984",
        "name": "KOMPA VIBE",
        "slug": "kompa-vibe",
        "type": "BRANCH",
        "parent_id": "1527367a-b025-4cf4-b653-0670dc7cd7e6",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#3b82f6",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": false
    },
    {
        "id": "d59c9864-e7b5-4038-8e2e-cf5e297d0abf",
        "name": "Kompa Vibe Paris",
        "slug": "kompa-vibe-paris",
        "type": "EVENT",
        "parent_id": "77da718e-86fe-461d-b416-435188f57984",
        "description": "Fiche détaillée pour Kompa Vibe Paris",
        "short_description": "Description courte de Kompa Vibe Paris",
        "content": "Contenu détaillé de Kompa Vibe Paris",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#06b6d4",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    },
    {
        "id": "ef7ff1ad-5c20-4c59-ab1c-b9dcae2f9d2e",
        "name": "AMAPIANO VIBE",
        "slug": "amapiano-vibe",
        "type": "BRANCH",
        "parent_id": "1527367a-b025-4cf4-b653-0670dc7cd7e6",
        "description": "",
        "short_description": "",
        "content": "",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "preset",
        "planet_type": "wire",
        "planet_color": "#22c55e",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "circle",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": false
    },
    {
        "id": "6fdcd72a-86a6-4959-bb02-f8c1e2b301cf",
        "name": "Amapiano Vibe Paris",
        "slug": "amapiano-vibe-paris",
        "type": "EVENT",
        "parent_id": "ef7ff1ad-5c20-4c59-ab1c-b9dcae2f9d2e",
        "description": "Fiche détaillée pour Amapiano Vibe Paris",
        "short_description": "Description courte de Amapiano Vibe Paris",
        "content": "Contenu détaillé de Amapiano Vibe Paris",
        "cta_text": "",
        "cta_url": "",
        "visual_source": "",
        "planet_type": "",
        "planet_color": "#eab308",
        "planet_scale": 0.8,
        "orbit_radius": 5.0,
        "orbit_speed": 0.15,
        "orbit_phase": 0.0,
        "orbit_position_y": 0.0,
        "orbit_shape": "",
        "orbit_roundness": 0.6,
        "rotation_speed": 1.0,
        "is_visible_3d": true
    }
]


class Command(BaseCommand):
    help = "Seed organization nodes from local fixture data"

    def handle(self, *args, **options):
        created = 0
        updated = 0

        # First pass: create nodes without parent
        for nd in NODES_DATA:
            obj, is_created = OrganizationNode.objects.update_or_create(
                id=nd["id"],
                defaults={k: v for k, v in nd.items() if k not in ("id", "parent_id")}
            )
            if is_created:
                created += 1
            else:
                updated += 1

        # Second pass: set parents
        for nd in NODES_DATA:
            if nd.get("parent_id"):
                try:
                    parent = OrganizationNode.objects.get(id=nd["parent_id"])
                    OrganizationNode.objects.filter(id=nd["id"]).update(parent=parent)
                except OrganizationNode.DoesNotExist:
                    pass

        self.stdout.write(self.style.SUCCESS(f"Done: {created} created, {updated} updated"))
