# Generated by Django 6.0.2 on 2026-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEACHER", "Enseignant"),
                    ("ORGANIZER", "Organisateur"),
                    ("ARTIST", "Artiste"),
                    ("CARE", "Praticien / Care"),
                    ("SHOP", "Boutique"),
                    ("COMMUNICATIONS", "Communication"),
                ],
                max_length=20,
                verbose_name="Rôle (Staff uniquement)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("STAFF", "Staff Capital of Fusion"),
                    ("MEMBER", "Membre"),
                ],
                default="MEMBER",
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
