# Generated by Django 6.0.2 on 2026-03-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff_member",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si cet artiste fait partie de l'équipe officielle CoF.",
                verbose_name="Membre du staff Capital of Fusion",
            ),
        ),
    ]
