# Generated by Django 6.0.2 on 2026-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_staff_role_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente de validation"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Refusé"),
                ],
                default="APPROVED",
                max_length=10,
                verbose_name="Statut du compte",
            ),
        ),
    ]
