# Generated by Django 6.0.2 on 2026-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_account_status_user_is_staff_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente de validation"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Refusé"),
                ],
                default="APPROVED",
                max_length=10,
                verbose_name="Statut du compte",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEACHER", "Enseignant"),
                    ("ORGANIZER", "Organisateur"),
                    ("ARTIST", "Artiste"),
                    ("CARE", "Praticien / Care"),
                    ("SHOP", "Boutique"),
                    ("COMMUNICATIONS", "Communication"),
                ],
                max_length=20,
                verbose_name="Rôle (Staff uniquement)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("STAFF", "Staff Capital of Fusion"),
                    ("MEMBER", "Membre"),
                ],
                default="MEMBER",
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
