# Generated by Django 6.0 on 2026-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_bio_en_user_bio_es"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/covers/",
                verbose_name="Image de couverture (profil public)",
            ),
        ),
    ]
