# Generated by Django 6.0 on 2026-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="profiles/covers/",
                verbose_name="Image de couverture (profil public)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="profiles/"
            ),
        ),
    ]
