# Generated by Django 6.0.2 on 2026-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_extend_image_field_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Instagram (max 3), sites web (max 3), Facebook, contact.",
                verbose_name="Liens & contact (réseaux)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="Artistes/covers/",
                verbose_name="Image de couverture (profil public)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="Artistes/"
            ),
        ),
    ]
