# Generated by Django 6.0 on 2026-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_profile_links_and_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="artist_display_order",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Plus petit = affiché en premier sur la page Artistes.",
                verbose_name="Ordre d'affichage (Artistes)",
            ),
        ),
    ]
