# Generated by Django 6.0 on 2026-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_video_url",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cycle_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                verbose_name="Fichier MP4 Cycle",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cycle_video_type",
            field=models.CharField(
                choices=[("youtube", "Vidéo YouTube"), ("mp4", "Fichier Local (MP4)")],
                default="youtube",
                max_length=10,
                verbose_name="Type Vidéo Cycle",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="cycle_video_youtube_id",
            field=models.CharField(
                blank=True,
                default="eZhq_RMYRKQ",
                max_length=50,
                verbose_name="ID YouTube Cycle",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="main_video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                verbose_name="Fichier MP4 Principale",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="main_video_type",
            field=models.CharField(
                choices=[("youtube", "Vidéo YouTube"), ("mp4", "Fichier Local (MP4)")],
                default="youtube",
                max_length=10,
                verbose_name="Type Vidéo Principale",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="main_video_youtube_id",
            field=models.CharField(
                blank=True,
                default="Dqg0oKlXpTE",
                max_length=50,
                verbose_name="ID YouTube Principale",
            ),
        ),
    ]
