# Generated by Django 6.0.2 on 2026-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_explorepreset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorepreset",
            name="camera_target_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="camera_target_y",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="camera_target_z",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="camera_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="camera_y",
            field=models.FloatField(default=6.84),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="camera_z",
            field=models.FloatField(default=18.79),
        ),
    ]
