# Generated by Django 6.0.2 on 2026-03-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_siteconfiguration_hero_video_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplorePreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Default Preset", max_length=255)),
                ("show_orbits", models.BooleanField(default=True)),
                ("freeze_planets", models.BooleanField(default=False)),
                ("show_debug_info", models.BooleanField(default=False)),
                ("fish_eye", models.FloatField(default=85)),
                ("light_config", models.JSONField(blank=True, default=dict)),
                ("orbit_spacing", models.FloatField(default=1)),
                ("global_planet_scale", models.FloatField(default=2.7)),
                ("global_shape_override", models.BooleanField(default=False)),
                ("orbit_shape", models.CharField(default="circle", max_length=50)),
                ("orbit_roundness", models.FloatField(default=0.6)),
                ("mouse_force", models.FloatField(default=0.5)),
                ("collision_force", models.FloatField(default=0.3)),
                ("damping", models.FloatField(default=0.92)),
                ("return_force", models.FloatField(default=0.08)),
                ("entry_stagger", models.FloatField(default=0)),
                ("entry_start_x", models.FloatField(default=-60)),
                ("entry_start_y", models.FloatField(default=0)),
                ("entry_start_z", models.FloatField(blank=True, null=True)),
                ("entry_speed_start", models.FloatField(default=2)),
                ("entry_speed_end", models.FloatField(default=8)),
                ("entry_easing", models.CharField(default="easeOut", max_length=50)),
                ("entry_duration", models.FloatField(default=3.5)),
                ("entry_trajectory", models.CharField(default="fan", max_length=50)),
                ("fan_distance", models.FloatField(default=30)),
                ("orbit_speed_start", models.FloatField(default=0)),
                ("orbit_speed_target", models.FloatField(default=0.5)),
                ("orbit_easing", models.CharField(default="easeOut", max_length=50)),
                ("orbital_ramp_duration", models.FloatField(default=0)),
                ("global_orbit_speed", models.FloatField(default=0.5)),
                ("grayscale_video", models.BooleanField(default=False)),
                ("enable_video_cycle", models.BooleanField(default=True)),
                ("video_cycle_visible", models.FloatField(default=10)),
                ("video_cycle_hidden", models.FloatField(default=10)),
                ("video_transition", models.IntegerField(default=1500)),
                ("show_video_overlay", models.BooleanField(default=False)),
                ("show_entry_trajectory", models.BooleanField(default=False)),
                ("vertical_mode", models.CharField(default="jupiter", max_length=50)),
                ("auto_distribute_orbits", models.BooleanField(default=True)),
                ("vertical_homogeneous_base", models.FloatField(default=5)),
                ("vertical_homogeneous_step", models.FloatField(default=20)),
                ("vertical_jupiter_amplitude", models.FloatField(default=30)),
                ("vertical_sphere_radius", models.FloatField(default=30)),
                ("hover_orbit_speed_ratio", models.FloatField(default=0.333)),
                ("hover_planet_speed_ratio", models.FloatField(default=0.1)),
                ("hover_orbit_transition_speed", models.FloatField(default=2)),
                ("hover_planet_transition_speed", models.FloatField(default=10)),
                ("is_transitioning_to_explore", models.BooleanField(default=False)),
                ("auto_reset_camera", models.BooleanField(default=False)),
                ("auto_reset_delay", models.FloatField(default=5)),
            ],
            options={
                "verbose_name": "Preset Explore 3D",
                "verbose_name_plural": "Presets Explore 3D",
            },
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="cycle_video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="cycle_video_type",
            field=models.CharField(
                choices=[("youtube", "Vidéo YouTube"), ("mp4", "Fichier Local (MP4)")],
                default="youtube",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="cycle_video_youtube_id",
            field=models.CharField(blank=True, default="eZhq_RMYRKQ", max_length=50),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="main_video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="main_video_type",
            field=models.CharField(
                choices=[("youtube", "Vidéo YouTube"), ("mp4", "Fichier Local (MP4)")],
                default="youtube",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="main_video_youtube_id",
            field=models.CharField(blank=True, default="Dqg0oKlXpTE", max_length=50),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="active_explore_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.explorepreset",
            ),
        ),
    ]
