# Generated by Django 6.0.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_explorepreset_camera_target_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_top_text",
            field=models.CharField(blank=True, default="Nouvelle Version Immersive", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_1",
            field=models.TextField(blank=True, default="Découvrez l'univers de la Bachata comme jamais."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_2",
            field=models.TextField(blank=True, default="Une expérience interactive en 3D au cœur de la danse."),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_1_text",
            field=models.CharField(blank=True, default="Commencer l'Expérience", max_length=100),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_1_url",
            field=models.CharField(blank=True, default="/explore", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_2_text",
            field=models.CharField(blank=True, default="Voir les Cours", max_length=100),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_2_url",
            field=models.CharField(blank=True, default="/cours", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_footer_text",
            field=models.CharField(blank=True, default="Paris, France • École Nationale de Danse", max_length=255),
        ),
    ]
