# Generated by Django 6.0.2 on 2026-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteconfiguration_hero_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorepreset",
            name="oscillation_amplitude",
            field=models.FloatField(
                default=0.3, help_text="Amplitude (unités) du mouvement vertical"
            ),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="oscillation_frequency",
            field=models.FloatField(
                default=0.5, help_text="Fréquence (Hz) de l'oscillation"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_title",
            field=models.CharField(
                blank=True, default="Capital of Fusion", max_length=255
            ),
        ),
    ]
