# Generated by Django 6.0.2 on 2026-03-07 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_oscillation_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content_markdown", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bulletin d'information",
                "verbose_name_plural": "Bulletins d'information",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="vision_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre vision (format Markdown).",
                verbose_name="Notre vision (Markdown)",
            ),
        ),
    ]
