# Generated by Django 6.0 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_pending_content_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="history_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre histoire (format Markdown).",
                verbose_name="Notre histoire (Markdown)",
            ),
        ),
    ]
