# Generated by Django 6.0.2 on 2026-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_identite_cof_history_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorepreset",
            name="orbit_zone_indicator_color",
            field=models.CharField(
                default="#a855f7",
                help_text="Couleur de l'anneau (ex. #a855f7 violet).",
                max_length=20,
                verbose_name="Couleur du cercle (hex)",
            ),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="orbit_zone_indicator_opacity",
            field=models.FloatField(
                default=0.28,
                help_text="Opacité de l'anneau (0 = transparent, 1 = opaque).",
                verbose_name="Opacité du cercle",
            ),
        ),
        migrations.AddField(
            model_name="explorepreset",
            name="show_orbit_zone_indicator",
            field=models.BooleanField(
                default=True,
                help_text="Affiche un anneau quand la souris est dans la zone où les planètes ralentissent.",
                verbose_name="Afficher le cercle de zone de ralentissement",
            ),
        ),
    ]
