# Generated by Django 6.0.2 on 2026-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_orbit_zone_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="content_markdown_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="content_markdown_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="content_markdown_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="danceprofession",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dancestyle",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="level",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_1_text_en",
            field=models.CharField(
                blank=True, default="Commencer l'Expérience", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_1_text_es",
            field=models.CharField(
                blank=True, default="Commencer l'Expérience", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_1_text_fr",
            field=models.CharField(
                blank=True, default="Commencer l'Expérience", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_2_text_en",
            field=models.CharField(
                blank=True, default="Voir les Cours", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_2_text_es",
            field=models.CharField(
                blank=True, default="Voir les Cours", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_btn_2_text_fr",
            field=models.CharField(
                blank=True, default="Voir les Cours", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_1_en",
            field=models.TextField(
                blank=True,
                default="Découvrez l'univers de la Bachata comme jamais.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_1_es",
            field=models.TextField(
                blank=True,
                default="Découvrez l'univers de la Bachata comme jamais.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_1_fr",
            field=models.TextField(
                blank=True,
                default="Découvrez l'univers de la Bachata comme jamais.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_2_en",
            field=models.TextField(
                blank=True,
                default="Une expérience interactive en 3D au cœur de la danse.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_2_es",
            field=models.TextField(
                blank=True,
                default="Une expérience interactive en 3D au cœur de la danse.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_descr_2_fr",
            field=models.TextField(
                blank=True,
                default="Une expérience interactive en 3D au cœur de la danse.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_footer_text_en",
            field=models.CharField(
                blank=True,
                default="Paris, France • École Nationale de Danse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_footer_text_es",
            field=models.CharField(
                blank=True,
                default="Paris, France • École Nationale de Danse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_footer_text_fr",
            field=models.CharField(
                blank=True,
                default="Paris, France • École Nationale de Danse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_subtitle_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_subtitle_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_subtitle_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_title_en",
            field=models.CharField(
                blank=True, default="Capital of Fusion", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_title_es",
            field=models.CharField(
                blank=True, default="Capital of Fusion", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_title_fr",
            field=models.CharField(
                blank=True, default="Capital of Fusion", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_top_text_en",
            field=models.CharField(
                blank=True,
                default="Nouvelle Version Immersive",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_top_text_es",
            field=models.CharField(
                blank=True,
                default="Nouvelle Version Immersive",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="hero_top_text_fr",
            field=models.CharField(
                blank=True,
                default="Nouvelle Version Immersive",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="history_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre histoire (format Markdown).",
                null=True,
                verbose_name="Notre histoire (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="history_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre histoire (format Markdown).",
                null=True,
                verbose_name="Notre histoire (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="history_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre histoire (format Markdown).",
                null=True,
                verbose_name="Notre histoire (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_name_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="site_name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="vision_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre vision (format Markdown).",
                null=True,
                verbose_name="Notre vision (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="vision_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre vision (format Markdown).",
                null=True,
                verbose_name="Notre vision (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="vision_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → Notre vision (format Markdown).",
                null=True,
                verbose_name="Notre vision (Markdown)",
            ),
        ),
    ]
