# Generated by Django 6.0.2 on 2026-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_pendingcontentedit_user_artist_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingcontentedit",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("siteconfig", "Configuration (Notre vision)"),
                    ("bulletin", "Bulletin"),
                    ("user_artist_bio", "Biographie artiste"),
                    ("user_artist_create", "Création artiste"),
                    ("event", "Événement"),
                    ("course", "Cours"),
                    ("theory_lesson", "Leçon de théorie"),
                    ("organization_node", "Noeud organisation"),
                    ("project", "Projet"),
                ],
                max_length=32,
            ),
        ),
    ]
