# Generated by Django 6.0 on 2026-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_danseur_cameraman_professions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVideoAmbience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grayscale_video",
                    models.BooleanField(
                        default=False, verbose_name="Vidéo en niveaux de gris"
                    ),
                ),
                (
                    "show_video_overlay",
                    models.BooleanField(
                        default=False,
                        verbose_name="Voile sombre sur la vidéo (option A)",
                    ),
                ),
                (
                    "enable_text_shadow",
                    models.BooleanField(
                        default=False, verbose_name="Ombre sur les textes (option B)"
                    ),
                ),
                (
                    "use_black_background",
                    models.BooleanField(
                        default=False,
                        verbose_name="Fond noir à la place de la vidéo (option C)",
                    ),
                ),
                (
                    "disable_youtube_iframes",
                    models.BooleanField(
                        default=False,
                        verbose_name="Désactiver les iframes YouTube (perf / test)",
                    ),
                ),
                (
                    "background_music_mode",
                    models.CharField(
                        choices=[
                            ("site", "Accueil (vidéos du site uniquement)"),
                            ("context", "Dédiées (musiques planètes / partenaires)"),
                        ],
                        default="context",
                        max_length=20,
                        verbose_name="Mode musique de fond",
                    ),
                ),
                (
                    "default_youtube_quality",
                    models.CharField(
                        choices=[
                            ("medium", "360p"),
                            ("large", "480p"),
                            ("hd720", "720p"),
                            ("hd1080", "1080p"),
                        ],
                        default="large",
                        help_text="Qualité initiale du lecteur principal (les visiteurs n’ont pas les boutons de réglage).",
                        max_length=20,
                        verbose_name="Qualité YouTube par défaut",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ambiance vidéo & texte (site public)",
                "verbose_name_plural": "Ambiance vidéo & texte (site public)",
            },
        ),
    ]
