# Generated by Django 6.0 on 2026-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_site_video_ambience"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (format Markdown).",
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (format Markdown).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (format Markdown).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (format Markdown).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_all_star_street_battle_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page All Star Street Bachata Battle (format Markdown).",
                verbose_name="Festival — All Star Street Battle (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_all_star_street_battle_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page All Star Street Bachata Battle (format Markdown).",
                null=True,
                verbose_name="Festival — All Star Street Battle (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_all_star_street_battle_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page All Star Street Bachata Battle (format Markdown).",
                null=True,
                verbose_name="Festival — All Star Street Battle (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_all_star_street_battle_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page All Star Street Bachata Battle (format Markdown).",
                null=True,
                verbose_name="Festival — All Star Street Battle (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_jack_n_jill_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Jack N Jill (format Markdown).",
                verbose_name="Festival — Jack N Jill (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_jack_n_jill_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Jack N Jill (format Markdown).",
                null=True,
                verbose_name="Festival — Jack N Jill (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_jack_n_jill_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Jack N Jill (format Markdown).",
                null=True,
                verbose_name="Festival — Jack N Jill (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_jack_n_jill_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Jack N Jill (format Markdown).",
                null=True,
                verbose_name="Festival — Jack N Jill (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_planning_navettes_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Planning & Navettes (format Markdown).",
                verbose_name="Festival — Planning & Navettes (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_planning_navettes_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Planning & Navettes (format Markdown).",
                null=True,
                verbose_name="Festival — Planning & Navettes (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_planning_navettes_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Planning & Navettes (format Markdown).",
                null=True,
                verbose_name="Festival — Planning & Navettes (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_planning_navettes_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Planning & Navettes (format Markdown).",
                null=True,
                verbose_name="Festival — Planning & Navettes (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_contact_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → Nous contacter (format Markdown).",
                verbose_name="Support — Nous contacter (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_contact_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → Nous contacter (format Markdown).",
                null=True,
                verbose_name="Support — Nous contacter (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_contact_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → Nous contacter (format Markdown).",
                null=True,
                verbose_name="Support — Nous contacter (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_contact_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → Nous contacter (format Markdown).",
                null=True,
                verbose_name="Support — Nous contacter (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_faq_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → FAQ (format Markdown).",
                verbose_name="Support — FAQ (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_faq_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → FAQ (format Markdown).",
                null=True,
                verbose_name="Support — FAQ (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_faq_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → FAQ (format Markdown).",
                null=True,
                verbose_name="Support — FAQ (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="support_faq_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Support → FAQ (format Markdown).",
                null=True,
                verbose_name="Support — FAQ (Markdown)",
            ),
        ),
    ]
