# Generated by Django 6.0 on 2026-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_siteconfiguration_festival_acces_venue_markdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your artiste (format Markdown).",
                verbose_name="Festival — Book your artiste (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your artiste (format Markdown).",
                null=True,
                verbose_name="Festival — Book your artiste (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your artiste (format Markdown).",
                null=True,
                verbose_name="Festival — Book your artiste (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your artiste (format Markdown).",
                null=True,
                verbose_name="Festival — Book your artiste (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Notre programme (format Markdown).",
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Notre programme (format Markdown).",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Notre programme (format Markdown).",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Notre programme (format Markdown).",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
    ]
