# Generated by Django 6.0 on 2026-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_siteconfiguration_festival_book_artiste_programme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_en",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_es",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="festival_book_your_artiste_markdown_fr",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_hotel_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your hôtel (format Markdown).",
                verbose_name="Festival — Book your hôtel (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_hotel_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your hôtel (format Markdown).",
                null=True,
                verbose_name="Festival — Book your hôtel (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_hotel_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your hôtel (format Markdown).",
                null=True,
                verbose_name="Festival — Book your hôtel (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="festival_book_your_hotel_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Book your hôtel (format Markdown).",
                null=True,
                verbose_name="Festival — Book your hôtel (Markdown)",
            ),
        ),
    ]
