# Generated by Django 6.0 on 2026-04-15 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_menuitem_book_your_hotel_internal_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("question_fr", models.CharField(max_length=500, null=True)),
                ("question_en", models.CharField(max_length=500, null=True)),
                ("question_es", models.CharField(max_length=500, null=True)),
                ("answer", models.TextField()),
                ("answer_fr", models.TextField(null=True)),
                ("answer_en", models.TextField(null=True)),
                ("answer_es", models.TextField(null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Entrée FAQ",
                "verbose_name_plural": "FAQ (questions / réponses)",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
