# Generated by Django 6.0 on 2026-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_menuitem_identite_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="identite_adn_festival_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → ADN du festival (format Markdown).",
                verbose_name="Identité COF — ADN du festival (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="identite_adn_festival_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → ADN du festival (format Markdown).",
                null=True,
                verbose_name="Identité COF — ADN du festival (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="identite_adn_festival_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → ADN du festival (format Markdown).",
                null=True,
                verbose_name="Identité COF — ADN du festival (Markdown)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="identite_adn_festival_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Identité COF → ADN du festival (format Markdown).",
                null=True,
                verbose_name="Identité COF — ADN du festival (Markdown)",
            ),
        ),
    ]
