# Generated by Django 6.0 on 2026-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_reorder_identite_adn_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Pour un enfant de menu : si décoché, ce lien n’apparaît pas dans le déroulant. Ignoré ou sans effet sur une entrée racine sans parent.",
                verbose_name="Visible (sous-menu)",
            ),
        ),
    ]
