# Generated by Django 5.2.13 on 2026-05-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_seed_festival_notre_programme_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Page Festival → Notre programme (Markdown). Trilingue via l’admin (FR / EN / ES). Vide partout : repli sur le texte i18n du frontend.",
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Page Festival → Notre programme (Markdown). Trilingue via l’admin (FR / EN / ES). Vide partout : repli sur le texte i18n du frontend.",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Page Festival → Notre programme (Markdown). Trilingue via l’admin (FR / EN / ES). Vide partout : repli sur le texte i18n du frontend.",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_notre_programme_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Page Festival → Notre programme (Markdown). Trilingue via l’admin (FR / EN / ES). Vide partout : repli sur le texte i18n du frontend.",
                null=True,
                verbose_name="Festival — Notre programme (Markdown)",
            ),
        ),
    ]
