# Generated by Django 5.2.13 on 2026-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_seed_festival_acces_venue_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (Markdown). Onglets FR/EN/ES. Si vide, le frontend affiche le fallback (festivalAccesVenueFallback.ts).",
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (Markdown). Onglets FR/EN/ES. Si vide, le frontend affiche le fallback (festivalAccesVenueFallback.ts).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_es",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (Markdown). Onglets FR/EN/ES. Si vide, le frontend affiche le fallback (festivalAccesVenueFallback.ts).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="festival_acces_venue_markdown_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu de la page Festival → Accès & Venue (Markdown). Onglets FR/EN/ES. Si vide, le frontend affiche le fallback (festivalAccesVenueFallback.ts).",
                null=True,
                verbose_name="Festival — Accès & Venue (Markdown)",
            ),
        ),
    ]
