# Generated by Django 5.2.13 on 2026-08-31 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_description_en_event_description_es_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalShuttleDeparture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.CharField(db_index=True, default="2026", max_length=8),
                ),
                (
                    "day_id",
                    models.CharField(help_text="jeu, ven, sam, dim", max_length=8),
                ),
                ("day_label", models.CharField(max_length=32)),
                ("day_date", models.CharField(help_text="ex. 17 sept.", max_length=32)),
                ("iso_date", models.DateField()),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("to_hotel", "Palmeraie → Hôtel"),
                            ("to_palmeraie", "Hôtel → Palmeraie"),
                        ],
                        max_length=16,
                    ),
                ),
                ("departure_time", models.CharField(help_text="HH:MM", max_length=5)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Départ navette festival",
                "verbose_name_plural": "Départs navettes festival",
                "ordering": ["iso_date", "direction", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["edition", "day_id", "direction"],
                        name="events_fest_edition_698b78_idx",
                    )
                ],
            },
        ),
    ]
