# Generated by Django 5.2.13 on 2026-08-31 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_seed_pbvf_2026_shuttle_departures"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalProgramSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.CharField(db_index=True, default="2026", max_length=8),
                ),
                (
                    "day_id",
                    models.CharField(help_text="jeu, ven, sam, dim", max_length=8),
                ),
                ("day_label", models.CharField(max_length=32)),
                ("day_date", models.CharField(help_text="ex. 17 sept.", max_length=32)),
                ("iso_date", models.DateField()),
                (
                    "room",
                    models.CharField(
                        help_text="La Casa Room, La Escuela, …", max_length=64
                    ),
                ),
                ("start_time", models.CharField(help_text="HH:MM", max_length=5)),
                ("end_time", models.CharField(help_text="HH:MM", max_length=5)),
                ("title", models.CharField(max_length=255)),
                (
                    "style",
                    models.CharField(
                        blank=True, help_text="Style / sous-titre", max_length=255
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("", "—"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("party", "Soirée"),
                            ("break", "Pause"),
                            ("competition", "Compétition"),
                            ("social", "Social"),
                            ("info", "Info"),
                            ("concert", "Concert"),
                        ],
                        default="workshop",
                        max_length=16,
                    ),
                ),
                ("is_live", models.BooleanField(default=False)),
                ("not_in_full_pass", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Créneau planning festival",
                "verbose_name_plural": "Créneaux planning festival",
                "ordering": ["iso_date", "room", "sort_order", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["edition", "day_id"],
                        name="events_fest_edition_905ce0_idx",
                    ),
                    models.Index(
                        fields=["edition", "room"],
                        name="events_fest_edition_3efbed_idx",
                    ),
                ],
            },
        ),
    ]
