# Generated by Django 5.2.13 on 2026-09-14 22:05

import uuid
from django.db import migrations, models


def seed_announcements(apps, schema_editor):
    FestivalAnnouncement = apps.get_model("events", "FestivalAnnouncement")
    if FestivalAnnouncement.objects.exists():
        return
    FestivalAnnouncement.objects.create(
        edition="2026",
        title="Bienvenue sur l’app PBVF",
        body="Les annonces urgentes s’affichent ici, sur tous les écrans. Tu peux fermer ce bandeau.",
        priority="urgent",
        is_published=True,
        sort_order=0,
    )
    FestivalAnnouncement.objects.create(
        edition="2026",
        title="Vérifie ton pass",
        body="Consulte le détail inclus / non inclus de chaque formule avant d’acheter des options.",
        priority="normal",
        is_published=True,
        link_url="/passes",
        link_label="Voir les passes",
        sort_order=1,
    )
    FestivalAnnouncement.objects.create(
        edition="2026",
        title="Code de conduite",
        body="Prends connaissance des règles Capital of Fusion avant le festival.",
        priority="normal",
        is_published=True,
        link_url="/code-of-conduct",
        link_label="Lire",
        sort_order=2,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_reseed_pbvf_2026_program_slots"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edition",
                    models.CharField(db_index=True, default="2026", max_length=16),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent (bandeau)"),
                            ("normal", "Normal (accueil)"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vide = visible dès publication",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, help_text="Vide = pas de fin automatique", null=True
                    ),
                ),
                ("link_url", models.CharField(blank=True, help_text="URL absolue ou chemin app (/passes, /code-of-conduct…)", max_length=500)),
                ("link_label", models.CharField(blank=True, max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Annonce festival",
                "verbose_name_plural": "Annonces festival",
                "ordering": ["-priority", "sort_order", "-created_at"],
            },
        ),
        migrations.RunPython(seed_announcements, migrations.RunPython.noop),
    ]
