# Generated by Django 5.2.13 on 2026-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushtoken",
            name="auth_key",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="endpoint",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="p256dh_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="token_type",
            field=models.CharField(
                choices=[("expo", "Expo Push"), ("webpush", "Web Push")],
                default="expo",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="token",
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name="pushtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("token_type", "expo")),
                fields=("token",),
                name="unique_expo_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="pushtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("token_type", "webpush")),
                fields=("endpoint",),
                name="unique_webpush_endpoint",
            ),
        ),
    ]
