# Generated by Django 5.2.13 on 2026-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_push_token_webpush"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushtoken",
            name="device_label",
            field=models.CharField(
                blank=True,
                help_text="Identification lisible de l'appareil (PWA installée / navigateur, user agent)",
                max_length=200,
            ),
        ),
    ]
