# Generated by Django 5.2.13 on 2026-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_push_token_device_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalannouncement",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="body_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="body_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="link_label_en",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="link_label_es",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="link_label_fr",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="title_es",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
