# Generated by Django 5.2.13 on 2026-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_festival_announcement_i18n_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="festivalannouncement",
            options={
                "ordering": ["-priority", "sort_order", "-created_at"],
                "verbose_name": "Notification / annonce",
                "verbose_name_plural": "Notifications / annonces",
            },
        ),
        migrations.AddField(
            model_name="festivalannouncement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("push", "Notif spontanée (push seul)"),
                    ("link", "Annonce avec redirection"),
                    ("info", "Annonce sans redirection"),
                    ("urgent", "Urgence (bandeau)"),
                ],
                db_index=True,
                default="info",
                help_text="push = notification téléphone uniquement. link = carte accueil + ouverture d'une page. info = carte accueil sans lien. urgent = bandeau en haut de toutes les pages.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="festivalannouncement",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="Obligatoire pour une annonce avec redirection (/passes, /code-of-conduct…)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="festivalannouncement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("urgent", "Urgent (bandeau)"),
                    ("normal", "Normal (accueil)"),
                ],
                db_index=True,
                default="normal",
                help_text="Dérivé automatiquement du type (urgent vs le reste).",
                max_length=16,
            ),
        ),
    ]
