# Generated by Django 6.0 on 2026-02-28 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_siteconfiguration_hero_video_url_and_more"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheoryLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rythme", "Rythme & Musique"),
                            ("technique", "Technique"),
                            ("histoire", "Histoire"),
                            ("culture", "Culture"),
                        ],
                        default="technique",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Contenu en Markdown"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="URL YouTube embed (optionnel)"
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theory_lessons",
                        to="core.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon de théorie",
                "verbose_name_plural": "Leçons de théorie",
                "ordering": ["category", "level__order"],
            },
        ),
    ]
