# Generated by Django 6.0.2 on 2026-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_theorylesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location_name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location_name_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="location_name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="content_en",
            field=models.TextField(
                blank=True, help_text="Contenu en Markdown", null=True
            ),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="content_es",
            field=models.TextField(
                blank=True, help_text="Contenu en Markdown", null=True
            ),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="content_fr",
            field=models.TextField(
                blank=True, help_text="Contenu en Markdown", null=True
            ),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theorylesson",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
