# Generated by Django 6.0.2 on 2026-03-08 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_identite_cof_vision_bulletins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/logos/",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ROOT", "Racine"),
                            ("BRANCH", "Branche"),
                            ("EVENT", "Événement"),
                        ],
                        default="BRANCH",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/nodes/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Contenu détaillé"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, default="En savoir plus", max_length=50
                    ),
                ),
                ("cta_url", models.CharField(blank=True, max_length=200)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="partners.partnernode",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure partenaire",
                "verbose_name_plural": "Structures partenaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FESTIVAL", "Festival"),
                            ("PARTY", "Soirée"),
                            ("WORKSHOP", "Atelier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/events/"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="partners.partnernode",
                        verbose_name="Structure partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement partenaire",
                "verbose_name_plural": "Événements partenaires",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/courses/"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_courses",
                        to="core.level",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_courses",
                        to="core.dancestyle",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taught_partner_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="partners.partnernode",
                        verbose_name="Structure partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours partenaire",
                "verbose_name_plural": "Cours partenaires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="partners.partnercourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire partenaire",
                "verbose_name_plural": "Horaires partenaires",
            },
        ),
    ]
