# Generated by Django 6.0.2 on 2026-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnernode",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Instagram (max 3), sites web (max 3), Facebook, contact.",
                verbose_name="Liens & contact",
            ),
        ),
        migrations.AddField(
            model_name="partnernode",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="partners/nodes/profiles/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
