# Generated by Django 6.0 on 2026-04-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_profile_links_and_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnernode",
            name="background_music",
            field=models.FileField(
                blank=True,
                help_text="MP3, OGG, etc. Si une URL YouTube est aussi renseignée, c’est YouTube qui est joué en priorité.",
                null=True,
                upload_to="partners/nodes/music/",
                verbose_name="Musique de fond (fichier)",
            ),
        ),
        migrations.AddField(
            model_name="partnernode",
            name="background_music_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Lien watch ou youtu.be ; la piste joue à la place du son des vidéos d’accueil sur la fiche structure.",
                max_length=512,
                verbose_name="Musique de fond (YouTube)",
            ),
        ),
    ]
