# Generated by Django 6.0.2 on 2026-04-05 10:05

import apps.partners.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partnernode_background_music"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnernode",
            name="background_music",
            field=models.FileField(
                blank=True,
                help_text="MP3, OGG, etc. Si une URL YouTube est aussi renseignée, c’est YouTube qui est joué en priorité.",
                null=True,
                storage=apps.partners.storage.PartnerBackgroundMusicStorage(),
                upload_to="partners/nodes/music/",
                verbose_name="Musique de fond (fichier)",
            ),
        ),
    ]
