# Generated by Django 6.0.2 on 2026-04-05 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partnernode_background_music_raw_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partnernode",
            name="linked_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Profils annuaire (utilisateurs avec au moins une profession danse).",
                related_name="linked_partner_structures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Artistes associés",
            ),
        ),
    ]
