# Generated by Django 6.0.2 on 2026-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_partnerevent_profile_cover_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerevent",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="partners/events/covers/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="partnerevent",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="partners/events/profiles/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
