# Generated by Django 6.0.2 on 2026-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_partnerevent_external_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercourse",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Instagram (max 3), sites web (max 3), Facebook, contact.",
                verbose_name="Liens & contact",
            ),
        ),
    ]
