# Generated by Django 6.0.2 on 2026-04-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_pendingcontentedit_content_type"),
        ("partners", "0009_partnercourse_external_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercourse",
            name="location_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Lieu (texte)"
            ),
        ),
        migrations.AddField(
            model_name="partnerschedule",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_schedules",
                to="core.level",
                verbose_name="Niveau (créneau)",
            ),
        ),
    ]
