# Generated by Django 6.0.2 on 2026-02-14 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Rôle organisation",
                "verbose_name_plural": "Rôles organisation",
            },
        ),
        migrations.CreateModel(
            name="OrganizationNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ROOT", "Racine"),
                            ("BRANCH", "Branche"),
                            ("EVENT", "Événement"),
                        ],
                        default="BRANCH",
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="organization/"),
                ),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField(blank=True)),
                ("cta_text", models.CharField(blank=True, max_length=255)),
                ("cta_url", models.CharField(blank=True, max_length=500)),
                ("visual_source", models.CharField(blank=True, max_length=100)),
                ("planet_type", models.CharField(blank=True, max_length=100)),
                ("model_3d", models.CharField(blank=True, max_length=255)),
                ("planet_texture", models.CharField(blank=True, max_length=255)),
                ("planet_color", models.CharField(blank=True, max_length=50)),
                ("orbit_radius", models.FloatField(blank=True, null=True)),
                ("orbit_speed", models.FloatField(blank=True, null=True)),
                ("planet_scale", models.FloatField(blank=True, null=True)),
                ("rotation_speed", models.FloatField(blank=True, null=True)),
                ("orbit_phase", models.FloatField(blank=True, null=True)),
                ("orbit_shape", models.CharField(blank=True, max_length=50)),
                ("orbit_roundness", models.FloatField(blank=True, null=True)),
                ("entry_start_x", models.FloatField(blank=True, null=True)),
                ("entry_start_y", models.FloatField(blank=True, null=True)),
                ("entry_start_z", models.FloatField(blank=True, null=True)),
                ("entry_speed", models.FloatField(blank=True, null=True)),
                ("is_visible_3d", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organization.organizationnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Noeud d'organisation",
                "verbose_name_plural": "Noeuds d'organisation",
            },
        ),
        migrations.CreateModel(
            name="NodeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="node_events/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("external_url", models.URLField(blank=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_events",
                        to="organization.organizationnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement noeud",
                "verbose_name_plural": "Événements noeud",
            },
        ),
        migrations.CreateModel(
            name="UserOrganizationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="organization.organizationrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle utilisateur sur un noeud",
                "verbose_name_plural": "Rôles utilisateurs sur noeuds",
                "unique_together": {("user", "node", "role")},
            },
        ),
    ]
