# Generated by Django 6.0.2 on 2026-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationnode",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Contenu riche affiché dans l'overlay (supporte le markdown)",
                verbose_name="Contenu détaillé",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Image principale affichée dans l'overlay (format 16:9 recommandé)",
                null=True,
                upload_to="nodes/covers/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="cta_text",
            field=models.CharField(
                blank=True,
                default="En savoir plus",
                help_text="Texte du bouton d'action principal",
                max_length=50,
                verbose_name="Texte du bouton CTA",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="Lien vers la page de destination (ex: /cours)",
                max_length=200,
                verbose_name="URL du bouton CTA",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="entry_speed",
            field=models.FloatField(
                default=0.4, help_text="Vitesse de la trajectoire d'entrée"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="entry_start_x",
            field=models.FloatField(
                default=-60.0, help_text="Position de départ X (ligne d'entrée)"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="entry_start_y",
            field=models.FloatField(
                default=0.0, help_text="Position de départ Y (ligne d'entrée)"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="entry_start_z",
            field=models.FloatField(
                blank=True,
                help_text="Position de départ Z (si null, utilise orbit_radius)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="is_visible_3d",
            field=models.BooleanField(
                default=True, help_text="Afficher cette planète dans la scène 3D"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="model_3d",
            field=models.FileField(
                blank=True,
                help_text="Utilisé si la source est 'Fichier GLB'",
                null=True,
                upload_to="planets/models/",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="orbit_phase",
            field=models.FloatField(
                default=0.0, help_text="Position initiale sur l'orbite (en radians)"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="orbit_radius",
            field=models.FloatField(
                default=5.0, help_text="Distance du centre (rayon de l'orbite)"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="orbit_roundness",
            field=models.FloatField(
                default=0.6, help_text="Pour Squircle : 0 = carré, 1 = cercle"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="orbit_shape",
            field=models.CharField(
                choices=[
                    ("circle", "Circulaire"),
                    ("squircle", "Squircle (Carré arrondi)"),
                ],
                default="circle",
                help_text="Forme de l'orbite",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="orbit_speed",
            field=models.FloatField(
                default=0.15, help_text="Vitesse de rotation orbitale"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_color",
            field=models.CharField(
                default="#7c3aed",
                help_text="Couleur de la planète (format hex: #RRGGBB)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_scale",
            field=models.FloatField(default=0.8, help_text="Taille de la planète"),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_texture",
            field=models.ImageField(
                blank=True,
                help_text="Utilisé si la source est 'Fichier GIF / Image'",
                null=True,
                upload_to="planets/textures/",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="planet_type",
            field=models.CharField(
                choices=[
                    ("wire", "Wireframe"),
                    ("dotted", "Dotted"),
                    ("glass", "Glass"),
                    ("chrome", "Chrome"),
                    ("network", "Network"),
                    ("star", "Starburst"),
                ],
                default="glass",
                help_text="Utilisé si la source est 'Préglage'",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="rotation_speed",
            field=models.FloatField(
                default=1.0, help_text="Vitesse de rotation sur elle-même"
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Description courte affichée sous le titre (max 300 caractères)",
                max_length=300,
                verbose_name="Accroche courte",
            ),
        ),
        migrations.AlterField(
            model_name="organizationnode",
            name="visual_source",
            field=models.CharField(
                choices=[
                    ("preset", "Préglage (Planet Type)"),
                    ("glb", "Fichier GLB"),
                    ("gif", "Fichier GIF / Image"),
                ],
                default="preset",
                help_text="Choisissez la source du visuel : un préglage paramétrique ou un fichier",
                max_length=10,
            ),
        ),
    ]
