# Generated by Django 6.0.2 on 2026-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organizationnode_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="orbit_position_y",
            field=models.FloatField(
                default=0.0,
                help_text="Position verticale (Y) manuelle de l'orbite (entre -50 et +50)",
            ),
        ),
    ]
