# Generated by Django 6.0.2 on 2026-03-03 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_organizationnode_orbit_position_y"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nom complet")),
                (
                    "role",
                    models.CharField(
                        help_text="Ex: Professeur, DJ, Vidéaste",
                        max_length=255,
                        verbose_name="Rôle / Fonction",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie courte")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organization/team/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "pole",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Pôle Enseignement, Pôle Média",
                        max_length=100,
                        verbose_name="Pôle d'appartenance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Membre actif"),
                ),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["role", "name"],
            },
        ),
    ]
