# Generated by Django 6.0 on 2026-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_populate_poles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="music_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier audio ou vidéo — utilisé si type = Fichier",
                null=True,
                upload_to="nodes/music/",
                verbose_name="Fichier musique",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="music_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Aucune"),
                    ("youtube", "Lien YouTube"),
                    ("file", "Fichier audio/vidéo"),
                ],
                default="",
                help_text="Jouée en fond quand l'overlay de cette planète est ouvert (remplace la vidéo d'accueil).",
                max_length=20,
                verbose_name="Type de musique de fond",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="music_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Ex: https://www.youtube.com/watch?v=VIDEO_ID — utilisé si type = Lien YouTube",
                verbose_name="URL YouTube (musique)",
            ),
        ),
    ]
