# Generated by Django 6.0.2 on 2026-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_organizationnode_music_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeevent",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="location_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="location_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="location_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nodeevent",
            name="title_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="content_en",
            field=models.TextField(
                blank=True,
                help_text="Contenu riche affiché dans l'overlay (supporte le markdown)",
                null=True,
                verbose_name="Contenu détaillé",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="content_es",
            field=models.TextField(
                blank=True,
                help_text="Contenu riche affiché dans l'overlay (supporte le markdown)",
                null=True,
                verbose_name="Contenu détaillé",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="content_fr",
            field=models.TextField(
                blank=True,
                help_text="Contenu riche affiché dans l'overlay (supporte le markdown)",
                null=True,
                verbose_name="Contenu détaillé",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cta_text_en",
            field=models.CharField(
                blank=True,
                default="En savoir plus",
                help_text="Texte du bouton d'action principal",
                max_length=50,
                null=True,
                verbose_name="Texte du bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cta_text_es",
            field=models.CharField(
                blank=True,
                default="En savoir plus",
                help_text="Texte du bouton d'action principal",
                max_length=50,
                null=True,
                verbose_name="Texte du bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="cta_text_fr",
            field=models.CharField(
                blank=True,
                default="En savoir plus",
                help_text="Texte du bouton d'action principal",
                max_length=50,
                null=True,
                verbose_name="Texte du bouton CTA",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="short_description_en",
            field=models.CharField(
                blank=True,
                help_text="Description courte affichée sous le titre (max 300 caractères)",
                max_length=300,
                null=True,
                verbose_name="Accroche courte",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="short_description_es",
            field=models.CharField(
                blank=True,
                help_text="Description courte affichée sous le titre (max 300 caractères)",
                max_length=300,
                null=True,
                verbose_name="Accroche courte",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="short_description_fr",
            field=models.CharField(
                blank=True,
                help_text="Description courte affichée sous le titre (max 300 caractères)",
                max_length=300,
                null=True,
                verbose_name="Accroche courte",
            ),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="name_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationrole",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pole",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom du pôle"
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="name_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom du pôle"
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="name_fr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom du pôle"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biographie courte"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biographie courte"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Biographie courte"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_es",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_fr",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_en",
            field=models.CharField(
                help_text="Ex: Professeur, DJ, Vidéaste",
                max_length=255,
                null=True,
                verbose_name="Rôle / Fonction",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_es",
            field=models.CharField(
                help_text="Ex: Professeur, DJ, Vidéaste",
                max_length=255,
                null=True,
                verbose_name="Rôle / Fonction",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_fr",
            field=models.CharField(
                help_text="Ex: Professeur, DJ, Vidéaste",
                max_length=255,
                null=True,
                verbose_name="Rôle / Fonction",
            ),
        ),
    ]
