# Generated by Django 6.0.2 on 2026-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0006_nodeevent_description_en_nodeevent_description_es_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="external_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Instagram (max 3), sites web (max 3), Facebook, contact.",
                verbose_name="Liens & contact",
            ),
        ),
        migrations.AddField(
            model_name="organizationnode",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Avatar affiché sur la fiche publique du nœud",
                null=True,
                upload_to="nodes/profiles/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
