# Generated by Django 5.2.13 on 2026-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_profile_links_and_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationnode",
            name="explore_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Plus la valeur est petite, plus le nœud apparaît tôt dans l’API /explore et le carrousel mobile. À égalité, tri par date de création.",
                verbose_name="Ordre Explore / carrousel",
            ),
        ),
    ]
