# Generated by GPT-5.2 on 2026-04-15

from __future__ import annotations

from django.db import migrations
from django.utils.text import slugify


def _unique_slug(base: str, used: set[str]) -> str:
    """
    Inputs:
        base: slug de base (déjà slugifié, peut être vide).
        used: ensemble des slugs déjà pris (en DB et dans cette exécution).
    Outputs:
        Un slug unique (suffixe -2, -3, ...) et ajouté à `used`.
    Purpose:
        Garantir l'unicité des slugs quand plusieurs nœuds ont le même `name`.
    """
    s = base or "node"
    if s not in used:
        used.add(s)
        return s
    i = 2
    while True:
        candidate = f"{s}-{i}"
        if candidate not in used:
            used.add(candidate)
            return candidate
        i += 1


def sync_node_slug_with_name(apps, schema_editor) -> None:
    OrganizationNode = apps.get_model("organization", "OrganizationNode")

    # Charger tous les slugs existants pour éviter les collisions.
    used = set(
        OrganizationNode.objects.exclude(slug__isnull=True)
        .exclude(slug__exact="")
        .values_list("slug", flat=True)
    )

    # On recalcul uniquement si `slug` n'est pas déjà égal à slugify(name).
    # Note: on applique aussi sur les nœuds non visibles 3D pour garder la règle simple et cohérente.
    for node in OrganizationNode.objects.all().only("id", "name", "slug"):
        desired_base = slugify(node.name or "", allow_unicode=False)
        desired = desired_base or "node"

        # Si déjà correct et non vide, ne rien faire.
        if node.slug and node.slug == desired:
            continue

        # Retirer l'ancien slug du set "used" (sinon on se bloque nous-mêmes),
        # puis choisir un slug unique.
        if node.slug:
            used.discard(node.slug)
        node.slug = _unique_slug(desired, used)
        node.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_profile_links_and_images"),
    ]

    operations = [
        migrations.RunPython(sync_node_slug_with_name, reverse_code=migrations.RunPython.noop),
    ]

