# Generated by Django 6.0 on 2026-03-11 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_pending_content_edit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nom du pass")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix (€)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "benefits",
                    models.JSONField(
                        default=list,
                        help_text="Liste des avantages du pass",
                        verbose_name="Avantages",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée (jours)"
                    ),
                ),
                (
                    "sessions_included",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null = illimité",
                        null=True,
                        verbose_name="Nombre de sessions incluses",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pass d'abonnement",
                "verbose_name_plural": "Pass d'abonnement",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nom instructeur (si externe)",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Date et heure")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Capacité max"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulé"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructeur",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.level",
                        verbose_name="Niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de training",
                "verbose_name_plural": "Sessions de training",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmé"),
                            ("waitlist", "Liste d'attente"),
                            ("cancelled", "Annulé"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="trainings.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription training",
                "verbose_name_plural": "Inscriptions training",
                "unique_together": {("user", "session")},
            },
        ),
    ]
