# Generated by Django 6.0.2 on 2026-03-03 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Adhésion annuelle, Pass 10 Sessions",
                        max_length=255,
                        verbose_name="Nom du Pass",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix (€)"
                    ),
                ),
                (
                    "validity_months",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Durée de validité (mois)"
                    ),
                ),
                (
                    "stripe_payment_url",
                    models.URLField(blank=True, verbose_name="Lien de paiement Stripe"),
                ),
            ],
            options={
                "verbose_name": "Pass / Abonnement",
                "verbose_name_plural": "Pass & Abonnements",
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateTimeField(verbose_name="Date et heure de la session"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Lieu")),
                (
                    "theme",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Thématique"
                    ),
                ),
                (
                    "available_spots",
                    models.PositiveIntegerField(verbose_name="Places disponibles"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Session active"),
                ),
            ],
            options={
                "verbose_name": "Session de training",
                "verbose_name_plural": "Sessions de training",
            },
        ),
    ]
