# Generated by Django 6.0.2 on 2026-03-03 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du praticien"),
                ),
                (
                    "specialty",
                    models.CharField(
                        max_length=255,
                        verbose_name="Spécialité (ex: Ostéopathie, Massage)",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie courte")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="care/practitioners/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "booking_url",
                    models.URLField(
                        blank=True, verbose_name="Lien de réservation (Doctolib, etc.)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Praticien",
                "verbose_name_plural": "Praticiens",
            },
        ),
        migrations.CreateModel(
            name="CareService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nom du soin")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description du soin"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Durée du soin en minutes",
                        verbose_name="Durée (minutes)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix indicatif (€)",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="care.practitioner",
                        verbose_name="Praticien associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soin",
                "verbose_name_plural": "Soins",
            },
        ),
    ]
